CREATE TABLE [dbo].[CM_Cars] (
    [UnqGUID]           UNIQUEIDENTIFIER    NOT NULL DEFAULT (newid()) ,
    [Name]              NVARCHAR (100)      NULL,
    Code                NVARCHAR (100)      NULL,
    Brand               NVARCHAR (100)      NULL,
    Class               NVARCHAR (100)      NULL,
    Price               DECIMAL(10, 2)      NULL,
    DateOfManufactring  DATETIME            NULL,
    IsActive            BIT                 NULL,
    SortOrder           DECIMAL(10, 2)      NULL,
    [Description]       NVARCHAR(MAX)       NULL,
    [Feature]           NVARCHAR(MAX)       NULL,
    [IsDeleted]         BIT                 NULL DEFAULT 0,
    [CreatedDate]       DATETIME            NULL DEFAULT GETUTCDATE(),
    [CreatedBy]         NVARCHAR (128)      NULL,
    [UpdatedDate]       DATETIME            NULL,
    [UpdatedBy]         NVARCHAR (128)      NULL,
    CONSTRAINT [PK_CMCar] PRIMARY KEY CLUSTERED ([UnqGUID] ASC),
);